# Michael Feldmann
version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      # Knoten-ID und Rollen
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      # Quorum f체r Controller des Knotens
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Listener f체r Broker und Controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      ALLOW_PLAINTEXT_LISTENER: "yes"
      # Advertised Listeners: Extern zug채ngliche Adresse
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    # Port-Mapping
    ports:
      - "9092:9092" # Broker-Port f체r externe Zugriffe
      - "9093:9093" # Controller-Port
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  kafka-data:
